name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
        
  deploy-dev:
    runs-on: ubuntu-latest
    environment: 
      name: Dev
      url: 'https://github.com/'
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
        
  deploy-hmg:
    runs-on: ubuntu-latest
    environment: 
      name: Hmg
      url: 'Google.com'
    needs: deploy-dev
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!


